using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace LibraryAPI.Models
{
    public class Category
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)] // This means that the Id will be generated by a database
        public int Id { get; set; }

        [Required]
        [MaxLength(50, ErrorMessage = "Category name cannot be longer than 50 characters")]
        public string  Name { get; set; }

        public ICollection<BookCategory> BookCategories { get; set; }
    }
}
