using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace LibraryAPI.Models
{
    public class Country
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)] // This means that the Id will be generated by a database
        public int Id { get; set; }

        [Required]
        [MaxLength(50, ErrorMessage = "Country name cannot be longer than 50 characters")]
        public string Name { get; set; }
        
        // virtual ICollection allows EF to use lazy loading
        public virtual ICollection<Author> Authors { get; set; }
    }
}
